from tkinter import *
ventana=Tk()
ventana.title("Uso de etiquetas y labels")
ventana.geometry("600x400")
marco1=Frame(ventana,width=600,height=50,bg="#FFABF2",border=2,relief="raised")
marco1.pack_propagate(False)
marco1.pack()
marco2=Frame(ventana,width=600,height=50,bg="#99ECFF",border=2,relief="raised")
marco2.pack_propagate(False)
marco2.pack()
marco3=Frame(ventana,width=600,height=50,bg="#F3C39E",border=2,relief="raised")
marco3.pack_propagate(False)
marco3.pack()
marco4=Frame(ventana,width=600,height=50,bg="#B7FFC2",border=2,relief="raised")
marco4.pack_propagate(False)
marco4.pack()
#Crear etiquetas
etiqueta1=Label(marco1,text="Dulce Dominguez Avila",bg="#FFABF2").pack(pady=10)
etiqueta2=Label(marco2,text="Universidad Tecnologica de Durango",bg="#99ECFF").pack(pady=10)
etiqueta3=Label(marco3,text="Tecnologias de la infomracion",bg="#F3C39E").pack(pady=10)
etiqueta4=Label(marco4,text="Desarrollo de Software Multiplataforma",bg="#B7FFC2").pack(pady=10)

ventana.mainloop()